spring:
   datasource:
      username: movie_review
      password: movie_review
      url: jdbc:mysql://localhost:3306/movie_review
      
   jpa:
      hibernate: 
         ddl-auto: none
      show-sql: true
      
   sql:
      init: 
         mode: never
